use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Serialize, Deserialize, sqlx::FromRow)]
#[sea_orm(table_name = "vendas")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub status: String,
    pub tipo: Option<String>,
    pub setor_id: i32,
    pub pdv: Uuid,
    pub turno_id: Option<Uuid>,
    pub turno_posto_id: Option<Uuid>,
    pub data_hora: Option<DateTime>,
    pub movimento: Option<DateTime>,
    pub automatico: Option<String>,
    pub subtotal: Option<Decimal>,
    pub desconto: Option<Decimal>,
    pub acrescimo: Option<Decimal>,
    pub valor_total: Option<Decimal>,
    pub troco: Option<Decimal>,
    pub desconto_itens: Option<Decimal>,
    pub acrescimo_itens: Option<Decimal>,
    pub parceiro_id: Option<i32>,
    pub dependente_id: Option<i32>,
    pub frota_id: Option<i32>,
    pub fidelidade_id: Option<i32>,
    pub tabela_preco_id: Option<i32>,
    pub cpf_cnpj: Option<String>,
    pub inscricao_estadual: Option<String>,
    pub ie_situacao: Option<String>,
    pub nome_fantasia: Option<String>,
    pub razao_social: Option<String>,
    pub logradouro: Option<String>,
    pub complemento: Option<String>,
    pub numero: Option<String>,
    pub bairro: Option<String>,
    pub municipio: Option<String>,
    pub cod_municipio: Option<i32>,
    pub uf: Option<String>,
    pub cep: Option<String>,
    pub km: Option<i32>,
    pub placa: Option<String>,
    pub condutor: Option<String>,
    pub unidade_consumidora: Option<String>,
    pub horimetro: Option<String>,
    pub pre_venda_id: Option<Uuid>,
    pub pre_venda_numero: Option<String>,
    pub nfe_contingencia: Option<String>,
    pub nfe_offline: Option<String>,
    pub nfe_aguardando_envio: Option<String>,
    pub nfe_tentativa_envio: Option<i32>,
    pub nfe_tipo: Option<i32>,
    pub nfe_data: Option<DateTime>,
    pub nfe_numero: Option<i32>,
    pub nfe_serie: Option<i32>,
    pub nfe_chave: Option<String>,
    pub nfe_protocolo: Option<String>,
    pub nfe_retorno: Option<String>,
    pub nfe_dados_adicionais: Option<String>,
    pub nfe_xml: Option<String>,
    pub nfe_arquivo: Option<String>,
    pub nfe_inconsistente: Option<String>,
    pub nfe_regerar: Option<String>,
    pub nfe_cancelamento_data: Option<DateTime>,
    pub nfe_cancelamento_motivo: Option<String>,
    pub nfe_cancelamento_protocolo: Option<String>,
    pub nfe_cancelamento_xml: Option<String>,
    pub nfe_cancelada: Option<String>,
    pub nfe_inutilizacao_data: Option<DateTime>,
    pub nfe_inutilizacao_protocolo: Option<String>,
    pub nfe_inutilizada: Option<String>,
    pub nfe_rejeicao: Option<String>,
    pub usuario_id: Option<i32>,
    pub vendedor_id: Option<i32>,
    pub usuario_pre_venda_id: Option<i32>,
    pub estorno: Option<String>,
    pub finalizada: Option<String>,
    pub atualiza_retaguarda: Option<String>,
    pub sincronizado: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}

pub type Venda = Model;
